#!/usr/bin/env python3
"""
Backlink Agent Orchestrator - Human Oversight Model

Daily runner for Scoring Zone backlink automation.
See backlink_automation_plan.md for full design.

HUMAN OVERSIGHT MODEL (as requested):
- Scheduled / "propose" runs: ONLY research + review. Never submit.
  Generates a Markdown report + shortlist JSON.
  The GitHub Action will turn this into a GitHub Issue for human review.
- "submit" runs: Only executed when a human manually triggers the workflow
  (via workflow_dispatch) and provides a list of approved targets.
  This keeps full human control over what actually gets submitted.

Environment variables (set in GitHub repo secrets + workflow):
    STEEL_API_KEY (required for any Steel calls)
    AGENT_MODE=propose | submit          (set by the workflow)
    APPROVED_TARGETS="Target1,Target2"   (only for submit mode)
    DRY_RUN=true | false

Usage (local testing):
    AGENT_MODE=propose python3 backlink_agent/orchestrator.py
    AGENT_MODE=submit APPROVED_TARGETS="Eat Sleep Golf - Get Listed" DRY_RUN=true python3 backlink_agent/orchestrator.py
"""

import os
import json
import sys
from datetime import datetime
from pathlib import Path

# Load .env file if present (for local development with keys)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # dotenv not installed, rely on real env vars

# Import our modules (they live in the same package).
# Handle both "python -m backlink_agent.orchestrator" (package) and direct script run.
try:
    from . import research as research_mod
except ImportError:
    # Direct script run: add dirs to path for "import research" and "import steel_utils" (from inside research).
    import sys
    pkg_dir = Path(__file__).parent
    sys.path.insert(0, str(pkg_dir))           # for "import research"
    sys.path.insert(0, str(pkg_dir.parent))    # for "import steel_utils" (sibling to backlink_agent)
    import research as research_mod

BASE_DIR = Path(__file__).parent.parent
LOGS_DIR = BASE_DIR / "logs"
DATA_DIR = BASE_DIR / "data"

LOGS_DIR.mkdir(exist_ok=True)
DATA_DIR.mkdir(exist_ok=True)


def log(message: str):
    timestamp = datetime.now().isoformat()
    line = f"[{timestamp}] {message}"
    print(line)
    with open(LOGS_DIR / f"daily_{datetime.now().strftime('%Y-%m-%d')}.log", "a") as f:
        f.write(line + "\n")


def load_config():
    return {
        "max_candidates_per_day": int(os.getenv("MAX_CANDIDATES_PER_DAY", "50")),
        "max_submissions_per_day": int(os.getenv("MAX_SUBMISSIONS_PER_DAY", "5")),
        "dry_run": os.getenv("DRY_RUN", "true").lower() in ("1", "true", "yes"),
        "min_authority_score": 75,
        "mode": os.getenv("AGENT_MODE", "propose").lower(),
        "approved_targets": os.getenv("APPROVED_TARGETS", "").strip(),
        "openrouter_api_key": os.getenv("OPENROUTER_API_KEY", "").strip(),
    }


def generate_proposal_report(scored_targets, date_str):
    """Generate a human-friendly Markdown report for the GitHub Issue."""
    report_lines = [
        f"# Backlink Proposals – {date_str}",
        "",
        "**Human Review Required** – This run only researched and scored targets. Nothing was submitted.",
        "",
        "Review the shortlist below. Reply to this issue with the targets you approve (e.g. `APPROVE: 1,3,5` or list names).",
        "Then manually trigger the workflow with `mode=submit` and the approved list in the `approved_targets` input.",
        "",
        f"**Total candidates researched:** {len(scored_targets)} (top {len(scored_targets)} shown after filtering)",
        "",
        "## Scored Shortlist (sorted by authority score)",
        "",
        "| # | Target | Score | Relevance | Why it fits | Recommended Action |",
        "|---|--------|-------|-----------|-------------|--------------------|",
    ]

    for idx, t in enumerate(scored_targets, 1):
        name = t.get("name", t.get("url", "Unknown"))
        score = t.get("score", 0)
        rel = t.get("topical_relevance", "N/A")
        why = t.get("justification", "")[:80].replace("\n", " ")
        action = t.get("recommended_action", "Review manually")
        report_lines.append(f"| {idx} | {name} | {score} | {rel} | {why} | {action} |")

    report_lines.extend([
        "",
        "## How to approve & submit",
        "1. Reply here with the numbers or names you want to proceed with.",
        "2. Go to the **Actions** tab → **Daily Backlink Agent** → **Run workflow**.",
        "3. Choose `mode=submit` and paste the approved names/IDs into `approved_targets` (comma separated).",
        "4. The submit job will only run what you explicitly approved.",
        "",
        "Full shortlist JSON (for reference): `data/shortlist_{}.json`".format(date_str),
        "",
        "_Generated by the Backlink Agent (human oversight mode). See `backlink_automation_plan.md` for details._",
    ])

    return "\n".join(report_lines)


def main():
    log("=== Scoring Zone Backlink Agent - Daily Run Starting ===")
    config = load_config()
    log(f"Config: {config}")

    mode = config["mode"]
    log(f"Running in mode: {mode}")

    if mode == "propose":
        # === RESEARCH + REVIEW ONLY (never submits) ===
        log("Phase 1: Research - Discovering new candidates...")
        try:
            candidates = research_mod.run(max_candidates=config["max_candidates_per_day"])
        except Exception as e:
            log(f"Research failed: {e}")
            candidates = []

        # Split: pre-vetted targets from the user's own list vs. newly discovered ones.
        seeded = [c for c in candidates if c.get("preapproved")]
        new_candidates = [c for c in candidates if not c.get("preapproved")]
        log(f"Research complete. {len(candidates)} candidates "
            f"({len(seeded)} from your list, {len(new_candidates)} newly discovered).")

        log("Phase 2: Review & Scoring against authority guidelines...")

        # Curated targets are already vetted by the user — include them directly (no score cutoff).
        scored_seeded = score_seeded_targets(seeded)

        # New discoveries go through the scorer + the authority threshold.
        openrouter_key = config.get("openrouter_api_key")
        if openrouter_key and new_candidates:
            log("Using OpenRouter (Grok via OpenRouter) to score new discoveries...")
            try:
                scored_new = score_candidates_with_openrouter(new_candidates, openrouter_key, config["min_authority_score"])
            except Exception as e:
                log(f"OpenRouter scoring failed ({e}), falling back to rule-based scorer.")
                scored_new = score_candidates_rule_based(new_candidates, config["min_authority_score"])
        else:
            if new_candidates:
                log("No OPENROUTER_API_KEY found — using built-in rule-based scorer for discoveries.")
            scored_new = score_candidates_rule_based(new_candidates, config["min_authority_score"])

        scored_new = [s for s in scored_new if s["score"] >= config["min_authority_score"]]
        scored_new.sort(key=lambda x: x["score"], reverse=True)
        scored_new = scored_new[: config["max_candidates_per_day"]]  # keep the list sane

        # Curated targets first (already sorted by seed score), then qualifying discoveries.
        scored = scored_seeded + scored_new

        # Hard floor: a curated, on-disk seed means this should be impossible — but never write
        # an empty list. If it ever happens, log loudly and fall back to every curated target.
        if not scored:
            log("WARNING: shortlist is empty after seeding+scoring — falling back to full curated list.")
            try:
                scored = score_seeded_targets(research_mod.all_tracker_targets())
            except Exception as e:
                log(f"Hard-floor fallback failed: {e}")

        log(f"Review complete. {len(scored)} targets on the shortlist "
            f"({len(scored_seeded)} curated, {len(scored_new)} new).")

        # Save shortlist for reference
        shortlist_path = DATA_DIR / f"shortlist_{datetime.now().strftime('%Y-%m-%d')}.json"
        with open(shortlist_path, "w") as f:
            json.dump(scored, f, indent=2)
        log(f"Shortlist saved to {shortlist_path}")

        # Generate human-readable report for the GitHub Issue
        date_str = datetime.now().strftime("%Y-%m-%d")
        report_md = generate_proposal_report(scored, date_str)
        report_path = DATA_DIR / f"daily_report_{date_str}.md"
        with open(report_path, "w") as f:
            f.write(report_md)
        log(f"Proposal report saved to {report_path}")

        # Also save a summary
        summary = {
            "date": date_str,
            "mode": "propose",
            "candidates_found": len(candidates),
            "seeded": len(seeded),
            "discovered": len(new_candidates),
            "shortlist_size": len(scored),
            "report_file": str(report_path),
            "shortlist_file": str(shortlist_path),
        }
        summary_path = DATA_DIR / f"summary_{date_str}.json"
        with open(summary_path, "w") as f:
            json.dump(summary, f, indent=2)

        log("PROPOSE run complete. A GitHub Issue should be created by the workflow for human review.")
        log("Nothing was submitted. Human must manually trigger with mode=submit after review.")

    elif mode == "submit":
        # === SUBMISSION ONLY - only runs when human explicitly triggers it ===
        approved_raw = config.get("approved_targets", "")
        if not approved_raw:
            log("No approved_targets provided for submit mode. Exiting.")
            return

        approved_list = [t.strip() for t in approved_raw.split(",") if t.strip()]
        log(f"Human-approved targets for submission: {approved_list}")

        if config["dry_run"]:
            log("DRY_RUN is true — would have submitted these targets but doing nothing.")
            for target in approved_list:
                log(f"  [DRY] Would submit: {target}")
        else:
            log("Submitting approved targets (real mode)...")
            # In a full implementation we would call submit logic here
            # For now we just log and update a simple tracker note
            for target in approved_list[: config["max_submissions_per_day"]]:
                log(f"  [SUBMIT] Executing submission for: {target}")
                # TODO: wire real submission using steel_utils + templates

            log("Submission phase finished. Update directory-submissions.md manually or via future submit module.")

    else:
        log(f"Unknown AGENT_MODE: {mode}. Valid values: propose, submit")

    log("=== End of Daily Backlink Agent Run ===")


def _action_from_status(status):
    s = (status or "").lower()
    if not s or "not submitted" in s or "ready" in s or "prepared" in s:
        return "Submit"
    if "submitted" in s or "pending" in s or "applied" in s or "progress" in s:
        return "Awaiting / verify"
    return "Review"


def score_seeded_targets(seeded):
    """Convert pre-vetted curated targets into shortlist entries directly (no score cutoff).

    These come from the user's own list, so they are always included — the rule-based scorer's
    golf-keyword heuristic must not drop them. Ordered by their seed score (priority).
    """
    out = []
    for c in seeded:
        status = (c.get("status") or "").strip()
        out.append({
            "name": c.get("name") or c.get("url", "") or "Unknown",
            "url": c.get("url", ""),
            "score": int(c.get("seed_score", 85)),
            "topical_relevance": "High",
            "justification": (c.get("notes") or "From your curated target list.")[:200].replace("\n", " "),
            "recommended_action": _action_from_status(status),
            "source": c.get("source", "Your target list"),
            "submission_method": "",
            "notes": status,
        })
    out.sort(key=lambda x: x["score"], reverse=True)
    return out


def score_candidates_rule_based(candidates, min_score):
    """Fallback simple rule-based scoring (golf-niche biased)."""
    scored = []
    for c in candidates:
        url = c.get("url", "")
        source = c.get("source", "")
        score = 60

        if any(kw in url.lower() for kw in ["golf", "eat sleep", "coach", "short game", "putting"]):
            score += 25
        if "eatsleepgolf" in url.lower() or "golf" in source.lower():
            score += 10
        if any(bad in url.lower() for bad in ["submit-your-site", "free-directory", "link-farm"]):
            score -= 30

        scored.append({
            "name": c.get("name", url.split("/")[-1] if url else "Unknown"),
            "url": url,
            "score": max(0, min(100, score)),
            "topical_relevance": "High" if score > 75 else "Medium",
            "justification": f"Source: {source}. Matched golf keywords." if score > 70 else "Generic directory.",
            "recommended_action": "Form submission via Steel" if score > 75 else "Manual review",
            "source": source,
        })

    scored = [s for s in scored if s["score"] >= min_score]
    scored.sort(key=lambda x: x["score"], reverse=True)
    return scored


def score_candidates_with_openrouter(candidates, api_key, min_score):
    """Score candidates using OpenRouter (can route to Grok, Claude, etc.)."""
    import requests

    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://github.com/stephenpickering79-tech/Scoringzonebacklinksagent",
        "X-Title": "Scoring Zone Backlink Agent",
    }

    scored = []
    prompt_template = open(BASE_DIR / "backlink_agent/prompts/scoring_prompt.txt").read()
    guidelines = open(BASE_DIR / "authority_guidelines.md").read()

    # You can change the model here. Examples:
    # "x-ai/grok-3" for Grok (via OpenRouter)
    # "anthropic/claude-3.5-sonnet" for Claude
    # "openai/gpt-4o" etc.
    model = "x-ai/grok-3"   # Using Grok via OpenRouter

    for c in candidates:
        url_c = c.get("url", "")
        title = c.get("title") or c.get("source", "")
        desc = c.get("description") or c.get("source", "") or url_c
        snippet = c.get("snippet", "")[:500]

        # Make the prompt self-contained by including the guidelines (the template references the .md but the LLM can't read files).
        prompt = f"""Here are the official Scoring Zone Backlink Authority Guidelines:

{guidelines}

---

Now follow the instructions below and score this candidate.

{prompt_template.format(
            url=url_c,
            title=title,
            description=desc,
            snippet=snippet
        )}"""

        payload = {
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.2,
            "max_tokens": 700,
            "response_format": {"type": "json_object"}  # Ask for JSON if the model supports it
        }

        resp = requests.post(url, headers=headers, json=payload, timeout=90)
        resp.raise_for_status()
        content = resp.json()["choices"][0]["message"]["content"].strip()

        # Try to parse JSON (the prompt asks for pure JSON)
        try:
            data = json.loads(content)
        except json.JSONDecodeError:
            # Fallback: try to extract JSON from the response
            import re
            match = re.search(r'\{.*\}', content, re.DOTALL)
            data = json.loads(match.group(0)) if match else {}

        score = int(data.get("overall_score", 50))
        if score >= min_score:
            scored.append({
                "name": data.get("name", url_c.split("/")[-1]),
                "url": url_c,
                "score": score,
                "topical_relevance": data.get("topical_relevance_score", "N/A"),
                "justification": data.get("justification", "Scored via OpenRouter"),
                "recommended_action": data.get("recommended_action", "Review manually"),
                "source": c.get("source", ""),
                "submission_method": data.get("submission_method", ""),
                "notes": data.get("notes", "")
            })

    scored.sort(key=lambda x: x["score"], reverse=True)
    return scored


if __name__ == "__main__":
    main()
