#!/usr/bin/env python3
"""
Backlink Agent Orchestrator - Human Oversight Model

Daily runner for Scoring Zone backlink automation.
See backlink_automation_plan.md for full design.

HUMAN OVERSIGHT MODEL (as requested):
- Scheduled / "propose" runs: ONLY research + review. Never submit.
  Generates a Markdown report + shortlist JSON.
  The GitHub Action will turn this into a GitHub Issue for human review.
- "submit" runs: Only executed when a human manually triggers the workflow
  (via workflow_dispatch) and provides a list of approved targets.
  This keeps full human control over what actually gets submitted.

Environment variables (set in GitHub repo secrets + workflow):
    STEEL_API_KEY (required for any Steel calls)
    AGENT_MODE=propose | submit          (set by the workflow)
    APPROVED_TARGETS="Target1,Target2"   (only for submit mode)
    DRY_RUN=true | false

Usage (local testing):
    AGENT_MODE=propose python3 backlink_agent/orchestrator.py
    AGENT_MODE=submit APPROVED_TARGETS="Eat Sleep Golf - Get Listed" DRY_RUN=true python3 backlink_agent/orchestrator.py
"""

import os
import json
import sys
from datetime import datetime
from pathlib import Path

# Import our modules (they live in the same package)
try:
    from . import research as research_mod
except ImportError:
    import research as research_mod

BASE_DIR = Path(__file__).parent.parent
LOGS_DIR = BASE_DIR / "logs"
DATA_DIR = BASE_DIR / "data"

LOGS_DIR.mkdir(exist_ok=True)
DATA_DIR.mkdir(exist_ok=True)


def log(message: str):
    timestamp = datetime.now().isoformat()
    line = f"[{timestamp}] {message}"
    print(line)
    with open(LOGS_DIR / f"daily_{datetime.now().strftime('%Y-%m-%d')}.log", "a") as f:
        f.write(line + "\n")


def load_config():
    return {
        "max_candidates_per_day": int(os.getenv("MAX_CANDIDATES", "50")),
        "max_submissions_per_day": int(os.getenv("MAX_SUBMISSIONS", "5")),
        "dry_run": os.getenv("DRY_RUN", "true").lower() in ("1", "true", "yes"),
        "min_authority_score": 75,
        "mode": os.getenv("AGENT_MODE", "propose").lower(),
        "approved_targets": os.getenv("APPROVED_TARGETS", "").strip(),
    }


def generate_proposal_report(scored_targets, date_str):
    """Generate a human-friendly Markdown report for the GitHub Issue."""
    report_lines = [
        f"# Backlink Proposals – {date_str}",
        "",
        "**Human Review Required** – This run only researched and scored targets. Nothing was submitted.",
        "",
        "Review the shortlist below. Reply to this issue with the targets you approve (e.g. `APPROVE: 1,3,5` or list names).",
        "Then manually trigger the workflow with `mode=submit` and the approved list in the `approved_targets` input.",
        "",
        f"**Total candidates researched:** {len(scored_targets)} (top {len(scored_targets)} shown after filtering)",
        "",
        "## Scored Shortlist (sorted by authority score)",
        "",
        "| # | Target | Score | Relevance | Why it fits | Recommended Action |",
        "|---|--------|-------|-----------|-------------|--------------------|",
    ]

    for idx, t in enumerate(scored_targets, 1):
        name = t.get("name", t.get("url", "Unknown"))
        score = t.get("score", 0)
        rel = t.get("topical_relevance", "N/A")
        why = t.get("justification", "")[:80].replace("\n", " ")
        action = t.get("recommended_action", "Review manually")
        report_lines.append(f"| {idx} | {name} | {score} | {rel} | {why} | {action} |")

    report_lines.extend([
        "",
        "## How to approve & submit",
        "1. Reply here with the numbers or names you want to proceed with.",
        "2. Go to the **Actions** tab → **Daily Backlink Agent** → **Run workflow**.",
        "3. Choose `mode=submit` and paste the approved names/IDs into `approved_targets` (comma separated).",
        "4. The submit job will only run what you explicitly approved.",
        "",
        "Full shortlist JSON (for reference): `data/shortlist_{}.json`".format(date_str),
        "",
        "_Generated by the Backlink Agent (human oversight mode). See `backlink_automation_plan.md` for details._",
    ])

    return "\n".join(report_lines)


def main():
    log("=== Scoring Zone Backlink Agent - Daily Run Starting ===")
    config = load_config()
    log(f"Config: {config}")

    mode = config["mode"]
    log(f"Running in mode: {mode}")

    if mode == "propose":
        # === RESEARCH + REVIEW ONLY (never submits) ===
        log("Phase 1: Research - Discovering new candidates...")
        try:
            candidates = research_mod.run(max_candidates=config["max_candidates_per_day"])
        except Exception as e:
            log(f"Research failed: {e}")
            candidates = []

        log(f"Research complete. Found {len(candidates)} raw candidates.")

        log("Phase 2: Review & Scoring against authority guidelines...")
        # Simple rule-based scoring for now (can be replaced by LLM later)
        scored = []
        for c in candidates:
            url = c.get("url", "")
            source = c.get("source", "")
            score = 60  # baseline

            # Boost for golf-specific signals (per authority_guidelines.md)
            if any(kw in url.lower() for kw in ["golf", "eat sleep", "coach", "short game", "putting"]):
                score += 25
            if "eatsleepgolf" in url.lower() or "golf" in source.lower():
                score += 10

            # Penalize generic low-value directories
            if any(bad in url.lower() for bad in ["submit-your-site", "free-directory", "link-farm"]):
                score -= 30

            scored.append({
                "name": c.get("name", url.split("/")[-1] if url else "Unknown"),
                "url": url,
                "score": max(0, min(100, score)),
                "topical_relevance": "High" if score > 75 else "Medium",
                "justification": f"Source: {source}. Matched golf keywords." if score > 70 else "Generic directory.",
                "recommended_action": "Form submission via Steel" if score > 75 else "Manual review",
                "source": source,
            })

        # Filter and sort
        scored = [s for s in scored if s["score"] >= config["min_authority_score"]]
        scored.sort(key=lambda x: x["score"], reverse=True)
        scored = scored[: config["max_submissions_per_day"] * 2]  # give human some choices

        log(f"Review complete. {len(scored)} targets passed the authority threshold.")

        # Save shortlist for reference
        shortlist_path = DATA_DIR / f"shortlist_{datetime.now().strftime('%Y-%m-%d')}.json"
        with open(shortlist_path, "w") as f:
            json.dump(scored, f, indent=2)
        log(f"Shortlist saved to {shortlist_path}")

        # Generate human-readable report for the GitHub Issue
        date_str = datetime.now().strftime("%Y-%m-%d")
        report_md = generate_proposal_report(scored, date_str)
        report_path = DATA_DIR / f"daily_report_{date_str}.md"
        with open(report_path, "w") as f:
            f.write(report_md)
        log(f"Proposal report saved to {report_path}")

        # Also save a summary
        summary = {
            "date": date_str,
            "mode": "propose",
            "candidates_found": len(candidates),
            "shortlist_size": len(scored),
            "report_file": str(report_path),
            "shortlist_file": str(shortlist_path),
        }
        summary_path = DATA_DIR / f"summary_{date_str}.json"
        with open(summary_path, "w") as f:
            json.dump(summary, f, indent=2)

        log("PROPOSE run complete. A GitHub Issue should be created by the workflow for human review.")
        log("Nothing was submitted. Human must manually trigger with mode=submit after review.")

    elif mode == "submit":
        # === SUBMISSION ONLY - only runs when human explicitly triggers it ===
        approved_raw = config.get("approved_targets", "")
        if not approved_raw:
            log("No approved_targets provided for submit mode. Exiting.")
            return

        approved_list = [t.strip() for t in approved_raw.split(",") if t.strip()]
        log(f"Human-approved targets for submission: {approved_list}")

        if config["dry_run"]:
            log("DRY_RUN is true — would have submitted these targets but doing nothing.")
            for target in approved_list:
                log(f"  [DRY] Would submit: {target}")
        else:
            log("Submitting approved targets (real mode)...")
            # In a full implementation we would call submit logic here
            # For now we just log and update a simple tracker note
            for target in approved_list[: config["max_submissions_per_day"]]:
                log(f"  [SUBMIT] Executing submission for: {target}")
                # TODO: wire real submission using steel_utils + templates

            log("Submission phase finished. Update directory-submissions.md manually or via future submit module.")

    else:
        log(f"Unknown AGENT_MODE: {mode}. Valid values: propose, submit")

    log("=== End of Daily Backlink Agent Run ===")


if __name__ == "__main__":
    main()
